Feature/1219 configurable drawer button
hajkmap/Hajk pull request #1255
Opened 2022-12-07 13:52 UTC by linusfj

Closes #1219.

2022-12-12 08:14 UTC, Hallbergs requested changes
It seems like the icon is placed a bit off, see image below:

![image](https://user-images.githubusercontent.com/43059093/206994347-353af3bb-33a4-46b7-a4c9-30ff03eec8ae.png)

The 8px margin you added is probably the culprit.

2022-12-16 07:12 UTC, Hallbergs commented
It is still off, check image below: 
![image](https://user-images.githubusercontent.com/43059093/208042065-c71f762f-9b71-4f2d-b5cf-850e52936b89.png)

Checking if `drawerButtonTitle` is nullish won't work since it is always set. We decide if we render it or not based on viewport size.

Also, just curious. Why an `<i>`-tag?

2022-12-20 15:30 UTC, linusfj commented
The icon has been updated to use a custom component instead, which has been styled to not add margin on some viewports.

2022-12-21 05:44 UTC, Hallbergs approved these changes

2022-12-21 05:45 UTC, merged