Feature/1267 refactor bookmarks plugin
hajkmap/Hajk pull request #1270
Opened 2023-01-20 14:10 UTC by linusfj

Closes #1267.

2023-01-20 14:35 UTC, jesade-vbg commented
Nice! It looks promising. I will check more and test next week. Had a quick check regarding storage format and it's indeed the parameters that are stored, including map name. Bookmarks are per domain not per map.

![image](https://user-images.githubusercontent.com/73874338/213723943-4f57a1eb-72ec-4664-bf94-0e668ba114e0.png)

2023-01-21 09:43 UTC, Hallbergs requested changes
I've just given it a quick look. Will give it a deeper dive next week. However, i have some questions right away:

 - Why are you rewriting and incorporating react functionality into `BookmarksModel.js`? This was just a regular js class, not a react class component (should/does not have to not be rewritten). Also i really don't think it a good idea with a react component(?) returning an object...? Or is this some kind of custom hook with bad naming? (Custom hooks should have the `use` keyword in front). I might just be too tired and missing something obvious. My main issue with this is that all our plugins are written with components along with one (or more) "model" (a regular js class). I don't see the point diverging from this "standard".
 - You "initialize" the model by writing `const bookmarksModel = BookmarksModel({ app, map });`. This code will run on every re-render of `Bookmarks.js` which is really unnecessary. You can look at the dummy-example where i thoroughly explain how this should be done.
 - `updateCustomProp` is unused and should be removed.

2023-01-23 06:53 UTC, jesade-vbg commented
I agree with Hallbergs comment. BookmarkModel.js should be kept as ordinary class, no reason to bloat it with react. I will look again and test when this is fixed.

2023-01-23 07:24 UTC, jacobwod commented
I agree with other reviewers. I think there's a clear example in the Dummy plugin. Otherwise check in e.g. Sketch.

2023-01-23 07:25 UTC, jacobwod requested changes
I agree with other reviewers. I think there's a clear example in the Dummy plugin. Otherwise check in e.g. Sketch.

2023-01-25 10:05 UTC, Hallbergs requested changes
I'm not sure if you're done? I checked the code again, and found some issues.

First of all, make sure we're compiling without warnings. See image below:
![image](https://user-images.githubusercontent.com/43059093/214532824-dd3d85bd-5b2d-4bf8-95aa-6aafbe6bd2f9.png)

The warnings stems from the fact that you've added stuff (from `Dummy`?) that are unnecessary, For example the `pluginShown` state was added in `Dummy` to show how to handle events from closing and opening the plugin window.

It also seems like you are adding a `localObserver` without actually using it. Not sure why.

2023-02-03 08:46 UTC, Hallbergs approved these changes

2023-02-03 11:18 UTC, merged