Allow setting a geometryField for edit layers with no features
hajkmap/Hajk pull request #1448
Opened 2023-12-14 08:50 UTC by sweco-secoma

closes #1447

2023-12-14 09:08 UTC, Hallbergs requested changes

2023-12-14 09:08 UTC, Hallbergs commented on new-admin/src/views/edit.jsx
> +                  title="Geometrifält som används ifall det finns inga befintliga features. om inte inställd 'geom' används"
~~Geometrifält som används ifall det finns inga befintliga features. om inte inställd 'geom' används~~ => 
Geometrifält som används om fältet inte kan hämtas genom WFS-tjänsten. Om inställningen saknas så kommer 'geom' att användas.

2023-12-14 09:08 UTC, Hallbergs commented on new-client/src/plugins/Edit/EditModel.js
> +    // Lastly, detfault to 'geom'. If we don't then OL will fallback to its own default geometry field name,
~~detfault~~ => default

Tip: A spell-checker in the code editor simplifies life!

2023-12-14 09:36 UTC, sweco-secoma commented
Thanks Henrik, have updated with your suggested changes. (Usually do have a spellchecker but it had not survived a change of computer - good catch, it's reinstalled now).

2023-12-15 11:41 UTC, Hallbergs approved these changes

2023-12-15 11:41 UTC, merged