Feature/1394 documenthandler front page
hajkmap/Hajk pull request #1520
Opened 2024-05-29 06:18 UTC by OlofSvahnVbg

closes #1394

2025-01-07 07:38 UTC, Hallbergs commented
What is the status on this one? Still relevant? @OlofSvahnVbg

2025-01-07 13:24 UTC, OlofSvahnVbg commented
Status is basically complete but could use some oversight. I can look at it tomorrow.

2025-01-08 13:04 UTC, OlofSvahnVbg commented
This is a certified lgtm.

2025-01-17 09:03 UTC, Hallbergs requested changes
Unfortunately i don't agree.

![image](https://github.com/user-attachments/assets/68cb5ec8-8700-463f-9c01-ea58d4094955)

Also, what is the deal with the lizard?
https://letsenhance.io/static/8f5e523ee6b2479e26ecc91b9c25261e/1015f/MainAfter.jpg

2025-03-04 08:27 UTC, closed without merging

2025-03-04 08:29 UTC, OlofSvahnVbg commented
Closing due to inactivity